apiVersion: v1
data:
  ENV: "dev"
 


  USER_STORE_DB: "viwell-user-store"


  VAR: "INPUT"
  EmailHost: "email-smtp.us-east-2.amazonaws.com"
  EmailPort: "465"
  EmailAccountType: "SES"
  ENV: "dev"
  DB: "viwell-email"
  SUPPORT_EMAIL: "care@viwell.com"
  OrgId: "779485866"
  DepartmentId: "730549000000820185"
  ZohoClientId: "1000.M6DGGY0Q49ZI1MC8UTPBFIUFH3XF3P"
  KSA_OBJECT_STORAGE_BUCKET_NAME: "viwell-email-templates-dev"
  KSA_OBJECT_STORAGE_REGION: "us-east-1"
  GLOBAL_OBJECT_STORAGE_BUCKET_NAME: "viwell-email-templates-dev"
  GLOBAL_OBJECT_STORAGE_REGION: "us-east-1"
  KSA_OBJECT_STORAGE_BUCKET_NAMESPACE: "viwell-email-templates-dev"

kind: ConfigMap
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
