apiVersion: v1
data:
  ENV: "dev"
 


  USER_STORE_DB: "viwell-user-store"


  VAR: "INPUT"
  PORT: "80"
  HOST: "0.0.0.0"
  JwtIss: "viwell.app"

kind: ConfigMap
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
